Repository gardener/gardener-extension-shoot-networking-problemdetector, pull requests merged in 2022-08, with the labels that each got.

#16 Improved dashboard queries
  charts/internal/shoot-network-problem-detector-controller-seed/nwpd-dashboard.json
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#17 Remove install-requirement and use tools.mk
  Makefile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#18 Add dashboard rows with details per jobid
  charts/internal/shoot-network-problem-detector-controller-seed/nwpd-dashboard.json
Labels: needs/ok-to-test, needs/second-opinion, size/l

#23 Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#28 Remove automountServiceAccountToken field for agents daemon sets
  go.mod
  go.sum
  pkg/controller/lifecycle/actuator.go
  vendor/github.com/gardener/network-problem-detector/pkg/common/utils.go
  vendor/github.com/gardener/network-problem-detector/pkg/deploy/agent.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs
