Repository gardener/gardener-extension-shoot-networking-problemdetector, pull requests merged in 2023-01, with the labels that each got.

#45 Drop support for kubernetes < 1.20 for networking problemdetector extension
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  go.mod
  hack/api-reference/config.json
  hack/api-reference/config.md
  pkg/controller/lifecycle/actuator.go
Labels: needs/ok-to-test, needs/review, size/s

#51 Adjustments for network-problem-detector v0.12
  charts/gardener-extension-shoot-networking-problemdetector/values.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/controller/lifecycle/actuator.go
  vendor/github.com/gardener/network-problem-detector/pkg/common/config/agent.go
  vendor/github.com/gardener/network-problem-detector/pkg/common/config/endpoint.go
  vendor/github.com/gardener/network-problem-detector/pkg/common/config/sample.go
  vendor/github.com/gardener/network-problem-detector/pkg/common/utils.go
  vendor/github.com/gardener/network-problem-detector/pkg/deploy/agent.go
  vendor/github.com/gardener/network-problem-detector/pkg/deploy/clusterconfig.go
  vendor/github.com/gardener/network-problem-detector/pkg/deploy/command.go
  vendor/modules.txt
Labels: kind/api-change, reviewed/lgtm, needs/ok-to-test, size/s

#52 Add CVE categorisation.
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
