Repository gardener/gardener-extension-shoot-networking-problemdetector, pull requests merged in 2025-04, with the labels that each got.

#227 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-shoot-networking-problemdetector/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#229 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#230 Update base image to `debian12`
  Dockerfile
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#232 Cleanup TODOs related to legacy monitoring configuration
  charts/gardener-extension-shoot-networking-problemdetector/templates/rbac.yaml
  charts/internal/shoot-network-problem-detector-controller-seed/templates/configmap-dashboards.yaml
  charts/internal/shoot-network-problem-detector-controller-seed/templates/configmap-observability.yaml
  charts/internal/shoot-network-problem-detector-controller-seed/templates/scrapeconfig.yaml
  charts/internal/shoot-network-problem-detector-controller-seed/values.yaml
  example/controller-registration.yaml
  pkg/controller/lifecycle/actuator.go
Labels: needs/ok-to-test, needs/review, size/s

#228 Remove wildcard RBAC references from Role and ClusterRole resources
  charts/gardener-extension-shoot-networking-problemdetector/templates/rbac.yaml
  example/25-rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/lgtm, needs/ok-to-test, needs/changes, needs/review, size/s

#234 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-networking-problemdetector/templates/rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test
